### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by SL-Pirate** [PHPeon/CustomIcons#1]
**This is not a bug but just a suggestion/request**

1)Why don't you consider posting some screenshots or something like that in the readme.md file cuz I don't think anyone might want to set it up without seeing it :)

2)And btw is that all the icons that are shown in the list? 

3)How am I supposed to set them up in my pc?? Please include that too in the readme file for noobies like me. :)

Congratulations for your effort.  :)

**Comment by PHPeon** [comment]
Hi SL-Pirate! Thank you kindly for your appreciation.

How to set them up can be found on "Home · PHPeon/CustomIcons Wiki" https://github.com/PHPeon/CustomIcons/wiki

It isn't a fully fledged theme yet, it's in very early versions, the icons themselves are meant to be exported in png/whatever format from a program like Adobe Ilustrator Inkscape or Gimp.

Remember, this is an unofficial "spin-off" of the Mint-Y icons, I'm curently just making icons for apps that are available on Linux but don't have an icon in the mint-y ofc repo or icons that are outdated and/or ugly.

I don't suggest you use them right away, I'm looking for colabs to help me.

**Comment by PHPeon** [comment]
No these are not all the icons, more are on the way.

**Comment by SL-Pirate** [comment]
> No these are not all the icons, more are on the way.

That's good news
