### ISSUE TITLE
how do i add icons?

### ISSUE THREAD

**Issue by chimpdev2** [PHPeon/CustomIcons#3]
Hello, i really like your icons and their designs, but i was wondering how i add them to my computer?

**Comment by PHPeon** [comment]
The icons themselves are really just for showcase currently and not a fully fledged theme, the idea behind them is to redesign old Mint-Y icons that look outdated or those who outright don't exist. Also if you're on windows i don't know how you'll even be able to change themes and icons

**Comment by chimpdev2** [comment]
ok thats fine!
