### ISSUE TITLE
 Please, could you do icons for simplenote, video-downloader and gnome-games-app?

### ISSUE THREAD

**Issue by ti-ago** [PHPeon/CustomIcons#5]

**Comment by ti-ago** [comment]
I would if I could

**Comment by PHPeon** [comment]
No prob I'll hope right on, but remember the mint y project has to evaluate individually every single one of my icons

**Comment by PHPeon** [comment]
I've made the simplenote one 

https://github.com/PHPeon/CustomIcons/blob/main/simplenote_assets.svg

it appears that all of your other requested icons already exist within the mint y repo
